# This service monitor belongs to the mock-server.yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-mock-gpu-monitor
  labels:
    app: prometheus-mock-gpu-monitor
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: gpu-metrics
      scheme: http
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  namespaceSelector:
    matchNames:
      - opendatahub

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-mock-gpu-monitor
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-mock-gpu-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-mock-gpu-monitor
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring