name: quay.tag
run-name: Creating new tag in quay based on pushed tag in github.
on:
  push:
    tags:
      - '*'
jobs:
  copy-tag-to-quay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -y update
      - run: sudo apt-get -y install podman
      - shell: bash
        env:
          QUAY_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
        run: |
         podman login quay.io -u mroman_redhat+odh_dashboard -p ${QUAY_TOKEN}
      - shell: bash
        env:
          TAG: ${{ git describe --tags }}
          HASH: ${{ git rev-parse --short HEAD }}
        run: |
         podman tag quay.io/opendatahub/odh-dashboard:main-${HASH} quay.io/opendatahub/odh-dashboard:${TAG}

